
version: '3'
services:
  django:
    image: e22263635c0d
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - static-files:/var/www/django/static/
    environment:
      - DJANGO_SECRET_KEY=r%zxa9wl^=5_j*6=a$$6onbtnu8(n&5j=f^@+ro4btgmi#=r)kd
      - DJANGO_DEBUG=False
#      URL='clubrobot.joelimgu.me'
      - URL=0.0.0.0:8000
      # Database options
      - DB_NAME=django
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - backend
    command: ["./wait-for-it.sh", "db:3306"]

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - 8080:80
    environment:
      - DJANGO_HOST=django
      - URL=http://django:8000
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - static-files:/www/static
    networks:
      - backend

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./bdd:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_DATABASE=django
    networks:
      - backend

networks:
  backend:

volumes:
  static-files: