# Generated by Django 4.0.5 on 2022-07-03 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='custom_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='estimated_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='is_in_use_internally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='manufacturer_description',
            field=models.CharField(default='undefined', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='recommended_stock',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
