# Generated by Django 4.0.5 on 2022-07-09 16:02

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_electricalcomponent_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricalcomponent',
            options={'ordering': ['-last_update']},
        ),
        migrations.AlterField(
            model_name='electricalcomponent',
            name='currency',
            field=models.ForeignKey(default=mainApp.models.get_default_currency, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.currency'),
        ),
        migrations.AlterField(
            model_name='electricalcomponent',
            name='reference',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
