# Generated by Django 4.1 on 2022-09-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_electricalcomponent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalcomponent',
            name='location',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
