# Generated by Django 4.1 on 2022-09-04 08:58

import colorfield.fields
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# mainApp.migrations.0007_auto_20220904_0754

class Migration(migrations.Migration):

    replaces = [('mainApp', '0006_tag_electricalcomponent_tags'), ('mainApp', '0007_auto_20220904_0754'), ('mainApp', '0008_alter_currency_name'), ('mainApp', '0009_tag_color')]

    dependencies = [
        ('mainApp', '0005_electricalcomponent_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='electricalcomponent',
            name='tags',
            field=models.ManyToManyField(related_name='electrical_components', to='mainApp.tag'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
