# Generated by Django 4.1 on 2022-09-04 07:54

from django.db import migrations
from django.db.migrations import RunPython


def nothing(*args):
    pass

def ensure_currency(apps, schema_editor):
    Currency = apps.get_model("mainApp", "Currency")
    try:
        Currency.objects.get(name="euro")
    except Currency.DoesNotExist:
        Currency(name="euro", symbol="€").save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_tag_electricalcomponent_tags'),
    ]

    operations = [
        RunPython(ensure_currency, reverse_code=nothing)
    ]
