# Generated by Django 4.1 on 2022-10-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_ensure_euro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalcomponent',
            name='location',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='electricalcomponent',
            name='recommended_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='StoreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.electricalcomponent')),
            ],
        ),
    ]
