# Generated by Django 4.1 on 2022-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_electricalcomponent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalcomponent',
            name='store_link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='StoreLink',
        ),
    ]
